# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(262, 521)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "MMRT Fitting Tool"))
        self.label_2.setText(_translate("Dialog", "Carlin Hamill, 2023\n"
"version 1.0"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "This software is licensed under the GNU GPLv3 liscence. See https://www.gnu.org/licenses/gpl-3.0.en.html for more details.\n"
"\n"
"This program uses open source libraries\n"
"- numpy (https://numpy.org/doc/stable/license.html)\n"
"- pandas (https://github.com/pandas-dev/pandas/blob/main/LICENSE)\n"
"- openpyxl (https://github.com/fluidware/openpyxl/blob/master/LICENCE)\n"
"- scipy (https://github.com/scipy/scipy/blob/main/LICENSE.txt)\n"
"- lmfit (https://github.com/lmfit/lmfit-py/blob/master/LICENSE)\n"
"- PyQt5 (https://www.riverbankcomputing.com/software/pyqt/)\n"
"- matplotlib (https://matplotlib.org/stable/users/project/license.html)\n"
"- numba (https://github.com/numba/numba/blob/main/LICENSE)\n"
"\n"
"Icons used in this application are sourced from:\n"
"\n"
"- Silk Icon set version 1.3 designed by Mark James (http://www.famfamfam.com/lab/icons/silk/) provided under a creative commons 2.5 Liscence (See https://creativecommons.org/licenses/by/2.5/ for more details).\n"
"\n"
"- Fugue Icon Set designed by Yusuke Kamiyamane (https://p.yusukekamiyamane.com/) provided under a creative commons 3.0 Liscence (See https://creativecommons.org/licenses/by/3.0/ for more details).\n"
"\n"
" - icon-icons.com sesigned by Nicky Lim (https://icon-icons.com/icon/import-download/176152) provided under a creative commons 4.0 Liscence (See https://creativecommons.org/licenses/by/4.0/ for more details).\n"
"\n"
"Calculation of conifidence intervals was adapted from code by John Kitchin (https://kitchingroup.cheme.cmu.edu/blog/2013/02/12/Nonlinear-curve-fitting-with-parameter-confidence-intervals/) provided under a Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license (See https://creativecommons.org/licenses/by-sa/4.0/deed.en_US for more details).\n"
"\n"
"For a copy of the source code or any questions about this program please email carlinhamill.mmrt@gmail.com"))
        self.pushButton.setText(_translate("Dialog", "View Licence"))
