# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen_widget2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1176, 781)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"    border:1px solid rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setChecked(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.pushButton_4)
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 278, 324))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7.addWidget(self.frame_3)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7.addWidget(self.frame_4)
        spacerItem = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.addWidget(self.scrollArea_4)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_5.setStyleSheet("QPushButton\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"    border:1px solid rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}")
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.buttonGroup_2.addButton(self.pushButton_5)
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 278, 324))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.scrollArea_3)
        self.horizontalLayout.addWidget(self.frame)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = MPLCanvas()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = MPLCanvas()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(260, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(260, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 238, 624))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 610, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"    border:1px solid rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}")
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setChecked(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_3)
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_6.setStyleSheet("QPushButton\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"    border:1px solid rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}")
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setChecked(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.buttonGroup.addButton(self.pushButton_6)
        self.verticalLayout.addWidget(self.pushButton_6)
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_4.setStatusTip(_translate("Form", "View and edit fit parameters"))
        self.pushButton_4.setText(_translate("Form", "View Parameters"))
        self.label.setText(_translate("Form", "Parameters:"))
        self.label_3.setText(_translate("Form", "Fit Parameters:"))
        self.label_4.setText(_translate("Form", "Starting Parameters:"))
        self.pushButton_5.setStatusTip(_translate("Form", "Edit dataset information"))
        self.pushButton_5.setText(_translate("Form", "Edit Dataset"))
        self.stackedWidget.setStyleSheet(_translate("Form", "QPushButton\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"    border:2px solid rgb(256, 256, 256);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(180,180,180,80);\n"
"}"))
        self.label_2.setText(_translate("Form", "Dataset:"))
        self.pushButton_3.setStatusTip(_translate("Form", "Analyse dataset with MMRT 1.0"))
        self.pushButton_3.setText(_translate("Form", "MMRT 1.0"))
        self.pushButton_6.setStatusTip(_translate("Form", "Analyse dataset with MMRT 1.5"))
        self.pushButton_6.setText(_translate("Form", "MMRT 1.5"))
from mfit.mfit1.custom_widgets import MPLCanvas
