# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_parameter_widget3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(354, 378)
        Form.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}\n"
"QLineEdit\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}\n"
"\n"
"QWidget#widget\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"}\n"
"QWidget#widget_2\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"}\n"
"QWidget#widget_3\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"}\n"
"QWidget#widget_4\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"}\n"
"QWidget#widget_5\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"}\n"
"QWidget#widget_6\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"}\n"
"QWidget#widget_7\n"
"{\n"
"    border:1px solid rgb(150, 150, 150);\n"
"}")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_8 = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_9.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(140, 0))
        self.label_13.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.verticalLayout_15.addWidget(self.widget_8)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.enthalpyLabel = QtWidgets.QLabel(self.widget)
        self.enthalpyLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.enthalpyLabel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.enthalpyLabel.setObjectName("enthalpyLabel")
        self.verticalLayout_11.addWidget(self.enthalpyLabel)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_7 = QtWidgets.QComboBox(self.widget)
        self.comboBox_7.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_7.setStyleSheet("QComboBox\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.verticalLayout.addWidget(self.comboBox_7)
        self.enthalpyLineEdit = QtWidgets.QLineEdit(self.widget)
        self.enthalpyLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.enthalpyLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.enthalpyLineEdit.setStyleSheet("border:1px solid rgb(182, 182, 182);")
        self.enthalpyLineEdit.setText("")
        self.enthalpyLineEdit.setObjectName("enthalpyLineEdit")
        self.verticalLayout.addWidget(self.enthalpyLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_15.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setStyleSheet("QWidget#widget\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.entropyLabel = QtWidgets.QLabel(self.widget_2)
        self.entropyLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.entropyLabel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.entropyLabel.setObjectName("entropyLabel")
        self.verticalLayout_12.addWidget(self.entropyLabel)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.comboBox_6 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_6.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_6.setStyleSheet("QComboBox\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_6)
        self.entropyLineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.entropyLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.entropyLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.entropyLineEdit.setText("")
        self.entropyLineEdit.setObjectName("entropyLineEdit")
        self.verticalLayout_7.addWidget(self.entropyLineEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_15.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setStyleSheet("QWidget#widget\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.enthalpyDifferenceLabel = QtWidgets.QLabel(self.widget_3)
        self.enthalpyDifferenceLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.enthalpyDifferenceLabel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.enthalpyDifferenceLabel.setObjectName("enthalpyDifferenceLabel")
        self.verticalLayout_14.addWidget(self.enthalpyDifferenceLabel)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_5.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_5.setStyleSheet("QComboBox\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_5)
        self.enthalpyDifferenceLineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.enthalpyDifferenceLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.enthalpyDifferenceLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.enthalpyDifferenceLineEdit.setText("")
        self.enthalpyDifferenceLineEdit.setObjectName("enthalpyDifferenceLineEdit")
        self.verticalLayout_6.addWidget(self.enthalpyDifferenceLineEdit)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_15.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setStyleSheet("QWidget#widget\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.heatCapacityUpperLabel = QtWidgets.QLabel(self.widget_4)
        self.heatCapacityUpperLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.heatCapacityUpperLabel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.heatCapacityUpperLabel.setObjectName("heatCapacityUpperLabel")
        self.verticalLayout_13.addWidget(self.heatCapacityUpperLabel)
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_4.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_4.setStyleSheet("QComboBox\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_4)
        self.heatCapacityUpperLineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.heatCapacityUpperLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.heatCapacityUpperLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.heatCapacityUpperLineEdit.setText("")
        self.heatCapacityUpperLineEdit.setObjectName("heatCapacityUpperLineEdit")
        self.verticalLayout_5.addWidget(self.heatCapacityUpperLineEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_15.addWidget(self.widget_4)
        self.widget_7 = QtWidgets.QWidget(Form)
        self.widget_7.setStyleSheet("QWidget#widget\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.heatCapacityLowerLabel = QtWidgets.QLabel(self.widget_7)
        self.heatCapacityLowerLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.heatCapacityLowerLabel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.heatCapacityLowerLabel.setObjectName("heatCapacityLowerLabel")
        self.verticalLayout_10.addWidget(self.heatCapacityLowerLabel)
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_2.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_2.setStyleSheet("QComboBox\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.heatCapacityLowerLineEdit = QtWidgets.QLineEdit(self.widget_7)
        self.heatCapacityLowerLineEdit.setEnabled(True)
        self.heatCapacityLowerLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.heatCapacityLowerLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.heatCapacityLowerLineEdit.setText("")
        self.heatCapacityLowerLineEdit.setReadOnly(True)
        self.heatCapacityLowerLineEdit.setObjectName("heatCapacityLowerLineEdit")
        self.verticalLayout_2.addWidget(self.heatCapacityLowerLineEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_15.addWidget(self.widget_7)
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setStyleSheet("QWidget#widget\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.TcLabel = QtWidgets.QLabel(self.widget_6)
        self.TcLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.TcLabel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.TcLabel.setObjectName("TcLabel")
        self.verticalLayout_9.addWidget(self.TcLabel)
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.widget_6)
        self.comboBox.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox.setStyleSheet("QComboBox\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.TcLineEdit = QtWidgets.QLineEdit(self.widget_6)
        self.TcLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.TcLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TcLineEdit.setText("")
        self.TcLineEdit.setReadOnly(True)
        self.TcLineEdit.setObjectName("TcLineEdit")
        self.verticalLayout_3.addWidget(self.TcLineEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_15.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setStyleSheet("QWidget#widget\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setMinimumSize(QtCore.QSize(140, 0))
        self.label_9.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_3.setStyleSheet("QComboBox\n"
"{\n"
"    border:1px solid rgb(182, 182, 182);\n"
"}")
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_3)
        self.tnLineEdit = QtWidgets.QLineEdit(self.widget_5)
        self.tnLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.tnLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tnLineEdit.setText("")
        self.tnLineEdit.setReadOnly(False)
        self.tnLineEdit.setObjectName("tnLineEdit")
        self.verticalLayout_4.addWidget(self.tnLineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_15.addWidget(self.widget_5)
        self.enthalpyLabel.setBuddy(self.enthalpyLineEdit)
        self.entropyLabel.setBuddy(self.entropyLineEdit)
        self.enthalpyDifferenceLabel.setBuddy(self.enthalpyDifferenceLineEdit)
        self.heatCapacityUpperLabel.setBuddy(self.heatCapacityUpperLineEdit)

        self.retranslateUi(Form)
        self.comboBox_2.setCurrentIndex(2)
        self.comboBox.setCurrentIndex(2)
        self.comboBox_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "Parameter:"))
        self.label_12.setText(_translate("Form", "Value:"))
        self.enthalpyLabel.setText(_translate("Form", "Enthalpy (&#8710;H<sub>T&#8320;</sub><sup>&Dagger;</sup>):"))
        self.label_4.setText(_translate("Form", "(J mol<sup>-1</sup>)"))
        self.comboBox_7.setStatusTip(_translate("Form", "Set parameter constraints"))
        self.comboBox_7.setItemText(0, _translate("Form", "Free"))
        self.comboBox_7.setItemText(1, _translate("Form", "Fixed"))
        self.enthalpyLineEdit.setStatusTip(_translate("Form", "Set starting value for parameter fit"))
        self.entropyLabel.setText(_translate("Form", "Entropy (&#8710;S<sub>T&#8320;</sub><sup>&Dagger;</sup>):"))
        self.label_5.setText(_translate("Form", "(J mol<sup>-1</sup> K<sup>-1</sup>)"))
        self.comboBox_6.setStatusTip(_translate("Form", "Set parameter constraints"))
        self.comboBox_6.setItemText(0, _translate("Form", "Free"))
        self.comboBox_6.setItemText(1, _translate("Form", "Fixed"))
        self.entropyLineEdit.setStatusTip(_translate("Form", "Set starting value for parameter fit"))
        self.enthalpyDifferenceLabel.setText(_translate("Form", "Enthalpy Difference (&#8710;&#8710;H<sup>&Dagger;</sup>):"))
        self.label_6.setText(_translate("Form", "(J mol<sup>-1</sup>)"))
        self.comboBox_5.setStatusTip(_translate("Form", "Set parameter constraints"))
        self.comboBox_5.setItemText(0, _translate("Form", "Free"))
        self.comboBox_5.setItemText(1, _translate("Form", "Fixed"))
        self.enthalpyDifferenceLineEdit.setStatusTip(_translate("Form", "Set starting value for parameter fit"))
        self.heatCapacityUpperLabel.setText(_translate("Form", "C<sub>P</sub> HighT (&#8710;C<sub>P,highT</sub><sup>&Dagger;</sup>):"))
        self.label_7.setText(_translate("Form", "(J mol<sup>-1</sup> K<sup>-1</sup>)"))
        self.comboBox_4.setStatusTip(_translate("Form", "Set parameter constraints"))
        self.comboBox_4.setItemText(0, _translate("Form", "Free"))
        self.comboBox_4.setItemText(1, _translate("Form", "Fixed"))
        self.heatCapacityUpperLineEdit.setStatusTip(_translate("Form", "Set starting value for parameter fit"))
        self.heatCapacityLowerLabel.setText(_translate("Form", "C<sub>P</sub> LowT (&#8710;C<sub>P,lowT</sub><sup>&Dagger;</sup>):"))
        self.label_3.setText(_translate("Form", "(J mol<sup>-1</sup> K<sup>-1</sup>)"))
        self.comboBox_2.setStatusTip(_translate("Form", "Set parameter constraints"))
        self.comboBox_2.setItemText(0, _translate("Form", "Custom"))
        self.comboBox_2.setItemText(1, _translate("Form", "Fixed"))
        self.comboBox_2.setItemText(2, _translate("Form", "Auto"))
        self.heatCapacityLowerLineEdit.setStatusTip(_translate("Form", "Set starting value for parameter fit"))
        self.TcLabel.setText(_translate("Form", "Transition Point (T<sub>C</sub>):"))
        self.label_2.setText(_translate("Form", "(K)"))
        self.comboBox.setStatusTip(_translate("Form", "Set parameter constraints"))
        self.comboBox.setItemText(0, _translate("Form", "Custom"))
        self.comboBox.setItemText(1, _translate("Form", "Fixed"))
        self.comboBox.setItemText(2, _translate("Form", "Auto"))
        self.TcLineEdit.setStatusTip(_translate("Form", "Set starting value for parameter fit"))
        self.label_9.setText(_translate("Form", "Reference Temperature (T<sub>0</sub>):"))
        self.label.setText(_translate("Form", "(K)"))
        self.comboBox_3.setStatusTip(_translate("Form", "Set parameter constraints"))
        self.comboBox_3.setItemText(0, _translate("Form", "Free"))
        self.comboBox_3.setItemText(1, _translate("Form", "Fixed"))
        self.tnLineEdit.setStatusTip(_translate("Form", "Set starting value for parameter fit"))
